// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuouyszuafzqvhpvcnsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1b3V5c3p1YWZ6cXZocHZjbnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NDQyMzYsImV4cCI6MjA4ODMyMDIzNn0.Xn49Pr6-RLXfKFtecJam-NgjtlK7few4hBoqo9xgDO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});